name: autodl
dependencies:
  - python=3.5
  - cudatoolkit=10.0
  - pip
  - pip:
    - hjson
    - pre-commit
    - hpbandster
    - matplotlib==3.0.3
    - numpy==1.16.2
    - opencv-python==4.1.0.25
    - pandas==0.24.2
    - pandocfilters==1.4.2
    - Pillow==6.0.0
    - psutil==5.6.2
    - PyYAML==5.1
    - scikit-learn==0.20.3
    - scipy==1.2.1
    - seaborn==0.9.0
    - six==1.12.0
    - tensorboard==1.13.0
    - tensorboardX
    - tensorflow-estimator==1.13.0
    - tensorflow-gpu==1.13.1
    - tensorflow-hub==0.5.0
    - torch==1.1.0
    - torchvision==0.3.0
