repos:
  - repo: https://github.com/pre-commit/mirrors-yapf
    rev: v0.27.0
    hooks:
      - id: yapf

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

  # - repo: https://gitlab.com/pycqa/flake8
  #   rev: 3.7.8
  #   hooks:
  #     - id: flake8

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: debug-statements
      - id: check-yaml
