repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-yaml
    -   id: debug-statements
    -   id: double-quote-string-fixer
    # -   id: check-json
    # -   id: name-tests-test
    # -   id: requirements-txt-fixer
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.1.6
    hooks:
    - id: remove-tabs
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3
      args: [--line-length 90 --target-version py35]
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v1.4.0
    hooks:
    -   id: reorder-python-imports
        language_version: python3
-   repo: https://github.com/asottile/add-trailing-comma
    rev: v1.0.0
    hooks:
    -   id: add-trailing-comma
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort
        args: [--multi-line=3 --trailing-comma --force-grid-wrap=0 --use-parentheses --line-width=90 -rc $SRC_FOLDER]
-   repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    -   id: autoflake
        args: ['--in-place', '--remove-all-unused-imports', '--remove-unused-variable']
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.7
    hooks:
    -   id: flake8
        additional_dependencies: [
          'flake8-blind-except',
          'flake8-commas',
          'flake8-comprehensions',
          'flake8-deprecated',
          'flake8-docstrings',
          'flake8-meiqia',
          'flake8-mutable',
          'flake8-pep3101',
          'flake8-quotes',
          'flake8-string-format',
          'flake8-tidy-imports',
          # These are good but are broken with current pydocstyle version
          # 'flake8-print',
          # 'flake8-debugger',
          # 'flake8-todo',
          ]
# -   repo: https://github.com/pre-commit/pre-commit
#     rev: v1.14.4
#     hooks:
#     -   id: validate_manifest
# -   repo: https://github.com/asottile/pyupgrade
#     rev: v1.12.0
#     hooks:
#     -   id: pyupgrade
-   repo: meta
    hooks:
    -   id: check-hooks-apply
    -   id: check-useless-excludes
