[tool.black]
line-length = 100
target-version = ['py35']

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap=0
use_parentheses = true

line_length = 100
force_single_line = true
atomic = true
lines_after_imports = 2
lines_between_types = 1
not_skip = "__init__.py"
filter_files = true
