name: autodl
channels:
  - pytorch
dependencies:
  - python=3.5
  - pytorch=1.0.1  # TODO: check competition version
  - cudatoolkit=10.0
  - torchvision=0.2.1  # TODO: check competition version
  - numpy
  - pip
  - isort
  - pip:
    - black
    - importchecker
